#include <stdio.h>
#include <stdlib.h>

#include "id3.h"

char *dataset[] =
{
// 	attr 1		attr 2		attr 3		attr 4		classes
"FEMALE",	   "INNER_CITY",      	"NO ",		"1",	 "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     	"3",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     	"0",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     	"3",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "YES",     	"0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     	"2",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "NO ",     	"0",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     	"0",     "YES_CAR",
"FEMALE",      "SUBURBAN  ",        "YES",     	"2",     "YES_CAR",
"MALE  ",      "TOWN      ",        "YES",     	"2",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     	"0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     	"0",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     	"1",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     	"1",     "YES_CAR",
"MALE  ",      "RURAL     ",        "YES",     	"0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "2",     "NO_CAR ",
"FEMALE",      "SUBURBAN  ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "2",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "2",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "2",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "1",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "3",     "YES_CAR",
"MALE  ",      "RURAL     ",        "YES",     "1",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "YES",     "2",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "2",     "NO_CAR ",
"MALE  ",      "SUBURBAN  ",        "YES",     "1",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "NO ",     "3",     "YES_CAR",
"MALE  ",      "SUBURBAN  ",        "NO ",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "2",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "YES",     "3",     "YES_CAR",
"FEMALE",      "RURAL     ",        "NO ",     "0",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "SUBURBAN  ",        "NO ",     "2",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"MALE  ",      "TOWN      ",        "NO ",     "2",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "2",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "2",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "1",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "2",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "NO ",     "2",     "YES_CAR",
"FEMALE",      "RURAL     ",        "YES",     "2",     "YES_CAR",
"MALE  ",      "TOWN      ",        "NO ",     "2",     "YES_CAR",
"MALE  ",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "SUBURBAN  ",        "NO ",     "1",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "NO ",     "3",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "NO ",     "1",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "1",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "1",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "2",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "NO ",     "2",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "NO ",     "0",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "NO ",     "2",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "YES",     "2",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "3",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "3",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "2",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "2",     "YES_CAR",
"FEMALE",      "RURAL     ",        "NO ",     "2",     "YES_CAR",
"FEMALE",      "TOWN      ",        "NO ",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "2",     "YES_CAR",
"FEMALE",      "TOWN      ",        "NO ",     "3",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "NO ",     "3",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "SUBURBAN  ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "2",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "1",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "NO ",     "2",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "NO ",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "2",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "2",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "NO ",     "2",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "YES",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "2",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"MALE  ",      "TOWN      ",        "NO ",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "3",     "YES_CAR",
"MALE  ",      "RURAL     ",        "YES",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "NO ",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "2",     "YES_CAR",
"MALE  ",      "TOWN      ",        "NO ",     "2",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "3",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"MALE  ",      "TOWN      ",        "NO ",     "2",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "2",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "3",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "NO ",     "0",     "YES_CAR",
"FEMALE",      "RURAL     ",        "YES",     "3",     "YES_CAR",
"MALE  ",      "RURAL     ",        "NO ",     "2",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "YES",     "1",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "1",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "NO ",     "1",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "NO ",     "3",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "2",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "3",     "YES_CAR",
"FEMALE",      "RURAL     ",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "2",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "YES",     "3",     "NO_CAR ",
"FEMALE",      "SUBURBAN  ",        "NO ",     "2",     "YES_CAR",
"FEMALE",      "SUBURBAN  ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "2",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "1",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "2",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "NO ",     "0",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "1",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "3",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "1",     "YES_CAR",
"MALE  ",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "SUBURBAN  ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "2",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "NO ",     "2",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "SUBURBAN  ",        "YES",     "3",     "YES_CAR",
"MALE  ",      "RURAL     ",        "YES",     "1",     "YES_CAR",
"MALE  ",      "TOWN      ",        "NO ",     "2",     "YES_CAR",
"MALE  ",      "TOWN      ",        "YES",     "2",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "NO ",     "2",     "YES_CAR",
"FEMALE",      "SUBURBAN  ",        "YES",     "2",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"MALE  ",      "RURAL     ",        "YES",     "2",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "2",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "NO ",     "3",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "NO ",     "1",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "NO ",     "1",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "NO ",     "1",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "2",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "3",     "YES_CAR",
"MALE  ",      "RURAL     ",        "YES",     "1",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "2",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "0",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "2",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "NO ",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "2",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "RURAL     ",        "YES",     "1",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "2",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "SUBURBAN  ",        "YES",     "2",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "YES_CAR",
"FEMALE",      "RURAL     ",        "YES",     "3",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"MALE  ",      "SUBURBAN  ",        "YES",     "2",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "2",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "2",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "1",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "NO ",     "3",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "TOWN      ",        "YES",     "1",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"MALE  ",      "TOWN      ",        "NO ",     "1",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "SUBURBAN  ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "SUBURBAN  ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "3",     "YES_CAR",
"MALE  ",      "TOWN      ",        "NO ",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "NO ",     "2",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "2",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "1",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "YES",     "3",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "2",     "YES_CAR",
"MALE  ",      "TOWN      ",        "NO ",     "0",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "1",     "NO_CAR ",
"MALE  ",      "SUBURBAN  ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "RURAL     ",        "NO ",     "3",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "1",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "NO ",     "2",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "2",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "YES",     "2",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"FEMALE",      "RURAL     ",        "YES",     "2",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"MALE  ",      "RURAL     ",        "YES",     "2",     "YES_CAR",
"MALE  ",      "SUBURBAN  ",        "NO ",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "NO ",     "3",     "YES_CAR",
"MALE  ",      "RURAL     ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "3",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "3",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "1",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "2",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "1",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "NO ",     "3",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "0",     "YES_CAR",
"FEMALE",      "SUBURBAN  ",        "NO ",     "2",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "2",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "NO ",     "3",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "NO ",     "0",     "NO_CAR ",
"MALE  ",      "SUBURBAN  ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "1",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "YES_CAR",
"MALE  ",      "TOWN      ",        "NO ",     "0",     "YES_CAR",
"FEMALE",      "SUBURBAN  ",        "NO ",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"MALE  ",      "TOWN      ",        "NO ",     "3",     "YES_CAR",
"FEMALE",      "SUBURBAN  ",        "NO ",     "2",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"MALE  ",      "RURAL     ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "SUBURBAN  ",        "NO ",     "1",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "1",     "YES_CAR",
"FEMALE",      "RURAL     ",        "NO ",     "0",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "3",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "3",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "3",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "YES",     "1",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "RURAL     ",        "YES",     "2",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "RURAL     ",        "NO ",     "2",     "YES_CAR",
"MALE  ",      "RURAL     ",        "YES",     "2",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "2",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "1",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "YES",     "3",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "NO ",     "3",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "NO ",     "2",     "YES_CAR",
"MALE  ",      "RURAL     ",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "TOWN      ",        "NO ",     "2",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "NO ",     "1",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "NO ",     "1",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "NO ",     "2",     "YES_CAR",
"FEMALE",      "RURAL     ",        "NO ",     "2",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"MALE  ",      "RURAL     ",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "2",     "YES_CAR",
"FEMALE",      "TOWN      ",        "NO ",     "1",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "2",     "NO_CAR ",
"MALE  ",      "SUBURBAN  ",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "2",     "YES_CAR",
"MALE  ",      "RURAL     ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "1",     "YES_CAR",
"MALE  ",      "TOWN      ",        "NO ",     "0",     "NO_CAR ",
"MALE  ",      "SUBURBAN  ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "NO ",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "NO ",     "1",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "3",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "YES",     "3",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "2",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "SUBURBAN  ",        "YES",     "2",     "NO_CAR ",
"FEMALE",      "SUBURBAN  ",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "2",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "YES_CAR",
"MALE  ",      "SUBURBAN  ",        "YES",     "2",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "SUBURBAN  ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "YES",     "1",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "YES",     "2",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "1",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "NO ",     "1",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "NO ",     "1",     "YES_CAR",
"FEMALE",      "SUBURBAN  ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "RURAL     ",        "YES",     "2",     "NO_CAR ",
"FEMALE",      "SUBURBAN  ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "NO ",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "3",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "1",     "YES_CAR",
"FEMALE",      "TOWN      ",        "NO ",     "2",     "YES_CAR",
"MALE  ",      "TOWN      ",        "YES",     "3",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "2",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "1",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "2",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "NO ",     "1",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"MALE  ",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "3",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "2",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "SUBURBAN  ",        "YES",     "2",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"FEMALE",      "TOWN      ",        "NO ",     "1",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "NO ",     "2",     "NO_CAR ",
"MALE  ",      "SUBURBAN  ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "3",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "NO ",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "2",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "1",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "3",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "NO ",     "1",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "NO ",     "0",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "3",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "2",     "YES_CAR",
"FEMALE",      "SUBURBAN  ",        "NO ",     "0",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "3",     "YES_CAR",
"MALE  ",      "RURAL     ",        "YES",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "2",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "1",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "RURAL     ",        "NO ",     "0",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "NO ",     "3",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "3",     "NO_CAR ",
"MALE  ",      "SUBURBAN  ",        "YES",     "3",     "YES_CAR",
"MALE  ",      "SUBURBAN  ",        "NO ",     "1",     "NO_CAR ",
"MALE  ",      "SUBURBAN  ",        "NO ",     "0",     "NO_CAR ",
"FEMALE",      "SUBURBAN  ",        "YES",     "1",     "YES_CAR",
"MALE  ",      "SUBURBAN  ",        "YES",     "2",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "1",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "NO ",     "2",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"FEMALE",      "SUBURBAN  ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "NO ",     "1",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "YES",     "1",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "2",     "YES_CAR",
"MALE  ",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "1",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"MALE  ",      "TOWN      ",        "NO ",     "1",     "YES_CAR",
"FEMALE",      "RURAL     ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "3",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "2",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "1",     "YES_CAR",
"MALE  ",      "RURAL     ",        "NO ",     "2",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "1",     "YES_CAR",
"MALE  ",      "TOWN      ",        "NO ",     "0",     "YES_CAR",
"FEMALE",      "RURAL     ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"MALE  ",      "TOWN      ",        "NO ",     "2",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "NO ",     "1",     "YES_CAR",
"FEMALE",      "SUBURBAN  ",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"FEMALE",      "RURAL     ",        "YES",     "0",     "YES_CAR",
"MALE  ",      "TOWN      ",        "NO ",     "0",     "YES_CAR",
"FEMALE",      "RURAL     ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "2",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "YES",     "3",     "YES_CAR",
"FEMALE",      "RURAL     ",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "3",     "YES_CAR",
"MALE  ",      "TOWN      ",        "NO ",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "NO ",     "0",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "SUBURBAN  ",        "NO ",     "1",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"FEMALE",      "SUBURBAN  ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"FEMALE",      "RURAL     ",        "YES",     "2",     "YES_CAR",
"MALE  ",      "TOWN      ",        "NO ",     "0",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "2",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "SUBURBAN  ",        "NO ",     "3",     "NO_CAR ",
"MALE  ",      "SUBURBAN  ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "NO ",     "3",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "2",     "YES_CAR",
"FEMALE",      "TOWN      ",        "NO ",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "NO ",     "1",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "2",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "NO ",     "1",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "2",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "NO ",     "1",     "YES_CAR",
"MALE  ",      "RURAL     ",        "YES",     "2",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "NO ",     "2",     "YES_CAR",
"MALE  ",      "RURAL     ",        "NO ",     "0",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "1",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "YES",     "1",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "3",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "2",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "1",     "YES_CAR",
"FEMALE",      "TOWN      ",        "NO ",     "1",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "0",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "YES",     "3",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "NO ",     "2",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "NO ",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "3",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "NO ",     "1",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "NO ",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "1",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "SUBURBAN  ",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "SUBURBAN  ",        "NO ",     "2",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "YES",     "2",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "3",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "RURAL     ",        "NO ",     "3",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "NO ",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "1",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "NO ",     "0",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "1",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "NO ",     "3",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "3",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "2",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "2",     "YES_CAR",
"MALE  ",      "SUBURBAN  ",        "NO ",     "3",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"MALE  ",      "SUBURBAN  ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "NO ",     "2",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "NO ",     "1",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "2",     "NO_CAR ",
"MALE  ",      "RURAL     ",        "YES",     "1",     "YES_CAR",
"MALE  ",      "SUBURBAN  ",        "YES",     "1",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "1",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "1",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"FEMALE",      "TOWN      ",        "NO ",     "1",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "1",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "NO ",     "2",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "1",     "YES_CAR",
"MALE  ",      "RURAL     ",        "YES",     "2",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "2",     "YES_CAR",
"MALE  ",      "SUBURBAN  ",        "YES",     "1",     "YES_CAR",
"MALE  ",      "RURAL     ",        "YES",     "1",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "0",     "YES_CAR",
"MALE  ",      "SUBURBAN  ",        "YES",     "2",     "YES_CAR",
"MALE  ",      "RURAL     ",        "YES",     "1",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "1",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "1",     "YES_CAR",
"MALE  ",      "SUBURBAN  ",        "YES",     "3",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "YES",     "2",     "YES_CAR",
"FEMALE",      "SUBURBAN  ",        "YES",     "0",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "3",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "2",     "YES_CAR",
"FEMALE",      "RURAL     ",        "YES",     "1",     "YES_CAR",
"MALE  ",      "RURAL     ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "SUBURBAN  ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "SUBURBAN  ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "INNER_CITY",        "NO ",     "1",     "NO_CAR ",
"FEMALE",      "SUBURBAN  ",        "NO ",     "0",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "1",     "NO_CAR ",
"MALE  ",      "SUBURBAN  ",        "YES",     "0",     "YES_CAR",
"MALE  ",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"MALE  ",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "YES",     "2",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "1",     "YES_CAR",
"FEMALE",      "RURAL     ",        "NO ",     "3",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "SUBURBAN  ",        "NO ",     "2",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "2",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"MALE  ",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "1",     "YES_CAR",
"MALE  ",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "NO ",     "0",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"MALE  ",      "SUBURBAN  ",        "YES",     "2",     "YES_CAR",
"MALE  ",      "TOWN      ",        "YES",     "2",     "YES_CAR",
"FEMALE",      "TOWN      ",        "NO ",     "3",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "NO ",     "2",     "YES_CAR",
"MALE  ",      "TOWN      ",        "YES",     "1",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "NO ",     "3",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "1",     "NO_CAR ",
"FEMALE",      "TOWN      ",        "NO ",     "1",     "YES_CAR",
"MALE  ",      "RURAL     ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "SUBURBAN  ",        "YES",     "1",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"FEMALE",      "INNER_CITY",        "NO ",     "2",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "SUBURBAN  ",        "YES",     "2",     "NO_CAR ",
"FEMALE",      "RURAL     ",        "YES",     "3",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "NO ",     "2",     "YES_CAR",
"FEMALE",      "INNER_CITY",        "YES",     "0",     "YES_CAR",
"FEMALE",      "TOWN      ",        "YES",     "0",     "YES_CAR",
"MALE  ",      "INNER_CITY",        "YES",     "0",     "NO_CAR ",
"MALE  ",      "TOWN      ",        "NO ",     "0",     "YES_CAR",
    NULL
};
char *dataset_weather[] =
{
	"SUNNY",  	"HOT",    	"HIGH",    	"WEAK",		"NO",
	"SUNNY",	"HOT",    	"HIGH",    	"STRONG",	"NO",
	"OVERCAST",	"HOT",    	"HIGH",   	"WEAK",		"YES",
	"RAIN",		"MILD",   	"HIGH",   	"WEAK",		"YES",
	"RAIN",		"COOL",		"NORMAL",  	"WEAK",		"YES",
	"RAIN",		"COOL",  	"NORMAL",  	"STRONG",	"NO",
	"OVERCAST",	"COOL",  	"NORMAL",  	"STRONG",	"YES",
	"SUNNY", 	"MILD",  	"HIGH",    	"WEAK",		"NO",
	"SUNNY", 	"COOL",  	"NORMAL",  	"WEAK",		"YES",
	"RAIN",		"MILD",  	"NORMAL",  	"WEAK",		"YES",
	"SUNNY", 	"MILD",  	"NORMAL",  	"STRONG",	"YES",
	"OVERCAST",	"MILD",  	"HIGH",    	"STRONG",	"YES",
	"OVERCAST",	"HOT", 		"NORMAL",  	"WEAK",		"YES",
	"RAIN",  	"MILD",  	"HIGH",		"STRONG",	"NO",
	NULL
};
char *dataset_lenses[] = 
{
	"young","myope","no","reduced no lenses",
	"young","myope","no","normal soft",
	"young","myope","yes","reduced no lenses",
	"young","myope","yes","normal hard",
	"young","hyper","no","reduced no lenses",
	"young","hyper","no","normal soft",
	"young","hyper","yes","reduced no lenses",
	"young","hyper","yes","normal hard",
	"pre",	"myope","no","reduced no lenses",
	"pre",	"myope","no","normal soft",
	"pre",	"myope","yes","reduced no lenses",
	"pre",	"myope","yes","normal hard",
	"pre",	"hyper","no","reduced no lenses",
	"pre",	"hyper","no","normal soft",
	"pre",	"hyper","yes","reduced no lenses",
	"pre",	"hyper","yes","normal no lenses",
	"presbyopic","myope","no","reduced no lenses",
	"presbyopic","myope","no","normal no lenses",
	"presbyopic","myope","yes","reduced no lenses",
	"presbyopic","myope","yes","normal hard",
	"presbyopic","hyper","no","reduced no lenses",
	"presbyopic","hyper","no","normal	soft",
	"presbyopic","hyper","yes","reduced no lenses",
	"presbyopic","hyper","yes","normal no lenses",
	NULL
};
int main()
{
    int result = 0;


    /*result = id3tree_create( 	dataset,			// puntatore al database
								5,					// totale colonne ( attributi + classi )
								120,					// totale samples nel database
								"sex",			// etichetta per attributo 1
								"region",		// etichetta per attributo 2
								"married",			// etichetta per attributo 3
								"children",				// etichetta per attributo 4
								"car",			// etichetta per classi
								NULL				// terminatore
							);*/
    result = id3tree_create( 	dataset_weather,			// puntatore al database
								5,					// totale colonne ( attributi + classi )
								14,					// totale samples nel database
								"outlook",			// etichetta per attributo 1
								"temp",		// etichetta per attributo 2
								"humi",			// etichetta per attributo 3
								"wind",				// etichetta per attributo 4
								"play",			// etichetta per classi
								NULL				// terminatore
							);
	/*result = id3tree_create( 	dataset_lenses,		
							4,					//  cols
							24,					// rows
							"age",			
							"prescription",		
							"astigmatic",			
							"tearRate",	
							NULL				// terminatore
						);*/				
    printf( "Esito: %d\n", result );


    return 0;
}
